services:
  terarium-llm-server:
    build: .
    container_name: terarium-llm-server
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-terarium-db-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    ports:
      - "18200:18200"
    volumes:
      - ./data:/app/data
